version: '3'
services:
  mysql-db:
    image: mysql:5.7.42
    container_name: devops-db
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=devops_project_db
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql
    networks:
      - my-network
  spring-boot-app:
    image: lotfitrabelsi/kaddembackend
    container_name: kaddembackend
    ports:
      - "8082:8089"
    restart: unless-stopped
    depends_on:
      - mysql-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://devops-db:3306/kaddem?&createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
    networks:
      - my-network
  front_app:
    build: ./etudiant-angular
    image: front
    restart: unless-stopped
    ports:
      - 80:80
    networks:
      - my-network
networks:
  my-network:      